/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteRouteImport } from './routes/_demo/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedWalletsRouteImport } from './routes/_authed/wallets'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedOverviewRouteImport } from './routes/_authed/overview'
import { Route as AuthedEventsRouteImport } from './routes/_authed/events'
import { Route as DemoDemoTanstackQueryRouteImport } from './routes/_demo/demo.tanstack-query'
import { Route as DemoDemoStoreRouteImport } from './routes/_demo/demo.store'
import { Route as DemoDemoStartServerFuncsRouteImport } from './routes/_demo/demo.start.server-funcs'
import { Route as DemoDemoStartApiRequestRouteImport } from './routes/_demo/demo.start.api-request'
import { Route as DemoDemoFormSimpleRouteImport } from './routes/_demo/demo.form.simple'
import { Route as DemoDemoFormAddressRouteImport } from './routes/_demo/demo.form.address'
import { ServerRoute as DemoApiDemoTqTodosServerRouteImport } from './routes/_demo/api.demo-tq-todos'
import { ServerRoute as DemoApiDemoNamesServerRouteImport } from './routes/_demo/api.demo-names'

const rootServerRouteImport = createServerRootRoute()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWalletsRoute = AuthedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOverviewRoute = AuthedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEventsRoute = AuthedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const DemoDemoTanstackQueryRoute = DemoDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDemoStoreRoute = DemoDemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDemoStartServerFuncsRoute =
  DemoDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => DemoRouteRoute,
  } as any)
const DemoDemoStartApiRequestRoute = DemoDemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDemoFormSimpleRoute = DemoDemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDemoFormAddressRoute = DemoDemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoApiDemoTqTodosServerRoute =
  DemoApiDemoTqTodosServerRouteImport.update({
    id: '/_demo/api/demo-tq-todos',
    path: '/api/demo-tq-todos',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const DemoApiDemoNamesServerRoute = DemoApiDemoNamesServerRouteImport.update({
  id: '/_demo/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof AuthedEventsRoute
  '/overview': typeof AuthedOverviewRoute
  '/settings': typeof AuthedSettingsRoute
  '/wallets': typeof AuthedWalletsRoute
  '/demo/store': typeof DemoDemoStoreRoute
  '/demo/tanstack-query': typeof DemoDemoTanstackQueryRoute
  '/demo/form/address': typeof DemoDemoFormAddressRoute
  '/demo/form/simple': typeof DemoDemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoDemoStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof AuthedEventsRoute
  '/overview': typeof AuthedOverviewRoute
  '/settings': typeof AuthedSettingsRoute
  '/wallets': typeof AuthedWalletsRoute
  '/demo/store': typeof DemoDemoStoreRoute
  '/demo/tanstack-query': typeof DemoDemoTanstackQueryRoute
  '/demo/form/address': typeof DemoDemoFormAddressRoute
  '/demo/form/simple': typeof DemoDemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoDemoStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_demo': typeof DemoRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/events': typeof AuthedEventsRoute
  '/_authed/overview': typeof AuthedOverviewRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/wallets': typeof AuthedWalletsRoute
  '/_demo/demo/store': typeof DemoDemoStoreRoute
  '/_demo/demo/tanstack-query': typeof DemoDemoTanstackQueryRoute
  '/_demo/demo/form/address': typeof DemoDemoFormAddressRoute
  '/_demo/demo/form/simple': typeof DemoDemoFormSimpleRoute
  '/_demo/demo/start/api-request': typeof DemoDemoStartApiRequestRoute
  '/_demo/demo/start/server-funcs': typeof DemoDemoStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/events'
    | '/overview'
    | '/settings'
    | '/wallets'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/overview'
    | '/settings'
    | '/wallets'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_demo'
    | '/auth'
    | '/_authed/events'
    | '/_authed/overview'
    | '/_authed/settings'
    | '/_authed/wallets'
    | '/_demo/demo/store'
    | '/_demo/demo/tanstack-query'
    | '/_demo/demo/form/address'
    | '/_demo/demo/form/simple'
    | '/_demo/demo/start/api-request'
    | '/_demo/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}
export interface FileServerRoutesByFullPath {
  '/api/demo-names': typeof DemoApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof DemoApiDemoTqTodosServerRoute
}
export interface FileServerRoutesByTo {
  '/api/demo-names': typeof DemoApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof DemoApiDemoTqTodosServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/_demo/api/demo-names': typeof DemoApiDemoNamesServerRoute
  '/_demo/api/demo-tq-todos': typeof DemoApiDemoTqTodosServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/demo-names' | '/api/demo-tq-todos'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/demo-names' | '/api/demo-tq-todos'
  id: '__root__' | '/_demo/api/demo-names' | '/_demo/api/demo-tq-todos'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  DemoApiDemoNamesServerRoute: typeof DemoApiDemoNamesServerRoute
  DemoApiDemoTqTodosServerRoute: typeof DemoApiDemoTqTodosServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/wallets': {
      id: '/_authed/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthedWalletsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/overview': {
      id: '/_authed/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthedOverviewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/events': {
      id: '/_authed/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthedEventsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_demo/demo/tanstack-query': {
      id: '/_demo/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoDemoTanstackQueryRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_demo/demo/store': {
      id: '/_demo/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoDemoStoreRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_demo/demo/start/server-funcs': {
      id: '/_demo/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoDemoStartServerFuncsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_demo/demo/start/api-request': {
      id: '/_demo/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoDemoStartApiRequestRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_demo/demo/form/simple': {
      id: '/_demo/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoDemoFormSimpleRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_demo/demo/form/address': {
      id: '/_demo/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoDemoFormAddressRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/_demo/api/demo-tq-todos': {
      id: '/_demo/api/demo-tq-todos'
      path: '/api/demo-tq-todos'
      fullPath: '/api/demo-tq-todos'
      preLoaderRoute: typeof DemoApiDemoTqTodosServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_demo/api/demo-names': {
      id: '/_demo/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof DemoApiDemoNamesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedEventsRoute: typeof AuthedEventsRoute
  AuthedOverviewRoute: typeof AuthedOverviewRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedWalletsRoute: typeof AuthedWalletsRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedEventsRoute: AuthedEventsRoute,
  AuthedOverviewRoute: AuthedOverviewRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedWalletsRoute: AuthedWalletsRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoDemoStoreRoute: typeof DemoDemoStoreRoute
  DemoDemoTanstackQueryRoute: typeof DemoDemoTanstackQueryRoute
  DemoDemoFormAddressRoute: typeof DemoDemoFormAddressRoute
  DemoDemoFormSimpleRoute: typeof DemoDemoFormSimpleRoute
  DemoDemoStartApiRequestRoute: typeof DemoDemoStartApiRequestRoute
  DemoDemoStartServerFuncsRoute: typeof DemoDemoStartServerFuncsRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoDemoStoreRoute: DemoDemoStoreRoute,
  DemoDemoTanstackQueryRoute: DemoDemoTanstackQueryRoute,
  DemoDemoFormAddressRoute: DemoDemoFormAddressRoute,
  DemoDemoFormSimpleRoute: DemoDemoFormSimpleRoute,
  DemoDemoStartApiRequestRoute: DemoDemoStartApiRequestRoute,
  DemoDemoStartServerFuncsRoute: DemoDemoStartServerFuncsRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  DemoApiDemoNamesServerRoute: DemoApiDemoNamesServerRoute,
  DemoApiDemoTqTodosServerRoute: DemoApiDemoTqTodosServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
